services:
  api:
    container_name: node-pedrobs-container
    build: .
    ports:
      - "2556:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CND_API_URL: ${CND_API_URL}
      CAPTCHA_API_KEY: ${CAPTCHA_API_KEY}
    restart: unless-stopped